default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PW'] %>
  host: localhost

development:
  <<: *default
  database: evt_dev

test:
  <<: *default
  database: evt_test

production:
  <<: *default
  database: evt

